Improve error message when X-Hub-Signature header is missing
Improvement over the previous error message of:

    NoMethodError (undefined method `bytesize' for nil:NilClass):

    activesupport (6.1.4.1) lib/active_support/security_utils.rb:34:in `secure_compare'
    github_webhook (1.2.0) lib/github_webhook/processor.rb:96:in `authenticate_github_request!'

This was discovered when doing some manual testing with curl.